[
  {
    "discussion_id": "2107381290",
    "pr_number": 7822,
    "pr_file": "api/pyproject.toml",
    "created_at": "2025-05-26T13:39:26+00:00",
    "commented_code": "\"celery[pytest] (>=5.4.0,<6.0.0)\",\n   \"dj-rest-auth[with_social,jwt] (==7.0.1)\",\n   \"django==5.1.8\",\n-  \"django-allauth==65.4.1\",\n+  \"django-allauth[saml] (>=65.8.0,<66.0.0)\",",
    "repo_full_name": "prowler-cloud/prowler",
    "discussion_comments": [
      {
        "comment_id": "2107381290",
        "repo_full_name": "prowler-cloud/prowler",
        "pr_number": 7822,
        "pr_file": "api/pyproject.toml",
        "discussion_id": "2107381290",
        "commented_code": "@@ -8,7 +8,7 @@ dependencies = [\n   \"celery[pytest] (>=5.4.0,<6.0.0)\",\n   \"dj-rest-auth[with_social,jwt] (==7.0.1)\",\n   \"django==5.1.8\",\n-  \"django-allauth==65.4.1\",\n+  \"django-allauth[saml] (>=65.8.0,<66.0.0)\",",
        "comment_created_at": "2025-05-26T13:39:26+00:00",
        "comment_author": "vicferpoy",
        "comment_body": "We need to make sure the social login still works as intended because we had hard dependencies between the `dj-rest-auth` library and `django-allauth`.",
        "pr_file_module": null
      },
      {
        "comment_id": "2107543285",
        "repo_full_name": "prowler-cloud/prowler",
        "pr_number": 7822,
        "pr_file": "api/pyproject.toml",
        "discussion_id": "2107381290",
        "commented_code": "@@ -8,7 +8,7 @@ dependencies = [\n   \"celery[pytest] (>=5.4.0,<6.0.0)\",\n   \"dj-rest-auth[with_social,jwt] (==7.0.1)\",\n   \"django==5.1.8\",\n-  \"django-allauth==65.4.1\",\n+  \"django-allauth[saml] (>=65.8.0,<66.0.0)\",",
        "comment_created_at": "2025-05-26T15:12:15+00:00",
        "comment_author": "AdriiiPRodri",
        "comment_body": "I checked it at the beginning of the development and it worked and I will check it again to be sure",
        "pr_file_module": null
      },
      {
        "comment_id": "2135931193",
        "repo_full_name": "prowler-cloud/prowler",
        "pr_number": 7822,
        "pr_file": "api/pyproject.toml",
        "discussion_id": "2107381290",
        "commented_code": "@@ -8,7 +8,7 @@ dependencies = [\n   \"celery[pytest] (>=5.4.0,<6.0.0)\",\n   \"dj-rest-auth[with_social,jwt] (==7.0.1)\",\n   \"django==5.1.8\",\n-  \"django-allauth==65.4.1\",\n+  \"django-allauth[saml] (>=65.8.0,<66.0.0)\",",
        "comment_created_at": "2025-06-09T15:21:15+00:00",
        "comment_author": "vicferpoy",
        "comment_body": "I will assume this was tested again and everything was correct. Thank you.",
        "pr_file_module": null
      }
    ]
  }
]