[
  {
    "discussion_id": "1803647969",
    "pr_number": 9271,
    "pr_file": "turborepo-tests/integration/tests/query/validation.t",
    "created_at": "2024-10-16T19:00:26+00:00",
    "commented_code": "+Setup\n+  $ . ${TESTDIR}/../../../helpers/setup_integration_test.sh persistent_dependencies/10-too-many\n+\n+Validate that we get an error when we try to run multiple persistent tasks with concurrency 1\n+  $ ${TURBO} run build --concurrency=1\n+    x invalid task configuration\n+  \n+  Error:   x You have 2 persistent tasks but `turbo` is configured for concurrency of\n+    | 1. Set --concurrency to at least 3\n+  \n+  [1]\n+\n+However on query, we ignore this validation\n+  $ ${TURBO} query \"query { packages { items { tasks { items { fullName } } } } }\" | jq\n+   WARNING  query command is experimental and may change in the future\n+  {\n+    \"data\": {\n+      \"packages\": {\n+        \"items\": [\n+          {\n+            \"tasks\": {\n+              \"items\": []\n+            }\n+          },\n+          {\n+            \"tasks\": {\n+              \"items\": [\n+                {\n+                  \"fullName\": \"one#build\"\n+                }\n+              ]\n+            }\n+          },\n+          {\n+            \"tasks\": {\n+              \"items\": [\n+                {\n+                  \"fullName\": \"two#build\"\n+                }\n+              ]\n+            }\n+          }\n+        ]\n+      }\n+    }\n+  }\n+\n+Setup\n+  $ . ${TESTDIR}/../../../helpers/setup_integration_test.sh task_dependencies/invalid-dependency\n+  warning: re-init: ignored --initial-branch=main\n+\n+Validate that we get an error when trying to depend on a task that doesn't exist\n+  $ ${TURBO} run build2\n+    x Could not find \"app-a#custom\" in root turbo.json or \"custom\" in package\n+      ,-[turbo.json:27:1]\n+   27 |       \"dependsOn\": [\n+   28 |         \"app-a#custom\"\n+      :         ^^^^^^^^^^^^^^\n+   29 |       ]\n+      `----\n+  \n+  [1]\n+\n+However, we don't get an error when we query",
    "repo_full_name": "vercel/turborepo",
    "discussion_comments": [
      {
        "comment_id": "1803647969",
        "repo_full_name": "vercel/turborepo",
        "pr_number": 9271,
        "pr_file": "turborepo-tests/integration/tests/query/validation.t",
        "discussion_id": "1803647969",
        "commented_code": "@@ -0,0 +1,148 @@\n+Setup\n+  $ . ${TESTDIR}/../../../helpers/setup_integration_test.sh persistent_dependencies/10-too-many\n+\n+Validate that we get an error when we try to run multiple persistent tasks with concurrency 1\n+  $ ${TURBO} run build --concurrency=1\n+    x invalid task configuration\n+  \n+  Error:   x You have 2 persistent tasks but `turbo` is configured for concurrency of\n+    | 1. Set --concurrency to at least 3\n+  \n+  [1]\n+\n+However on query, we ignore this validation\n+  $ ${TURBO} query \"query { packages { items { tasks { items { fullName } } } } }\" | jq\n+   WARNING  query command is experimental and may change in the future\n+  {\n+    \"data\": {\n+      \"packages\": {\n+        \"items\": [\n+          {\n+            \"tasks\": {\n+              \"items\": []\n+            }\n+          },\n+          {\n+            \"tasks\": {\n+              \"items\": [\n+                {\n+                  \"fullName\": \"one#build\"\n+                }\n+              ]\n+            }\n+          },\n+          {\n+            \"tasks\": {\n+              \"items\": [\n+                {\n+                  \"fullName\": \"two#build\"\n+                }\n+              ]\n+            }\n+          }\n+        ]\n+      }\n+    }\n+  }\n+\n+Setup\n+  $ . ${TESTDIR}/../../../helpers/setup_integration_test.sh task_dependencies/invalid-dependency\n+  warning: re-init: ignored --initial-branch=main\n+\n+Validate that we get an error when trying to depend on a task that doesn't exist\n+  $ ${TURBO} run build2\n+    x Could not find \"app-a#custom\" in root turbo.json or \"custom\" in package\n+      ,-[turbo.json:27:1]\n+   27 |       \"dependsOn\": [\n+   28 |         \"app-a#custom\"\n+      :         ^^^^^^^^^^^^^^\n+   29 |       ]\n+      `----\n+  \n+  [1]\n+\n+However, we don't get an error when we query",
        "comment_created_at": "2024-10-16T19:00:26+00:00",
        "comment_author": "chris-olszewski",
        "comment_body": "Up to you since you're the one driving `query`, but returning information that we know is incorrect feels off to me. Do we need to worry about panics down the line in query around assumptions that every task has a valid package and has valid task dependencies?",
        "pr_file_module": null
      },
      {
        "comment_id": "1803656129",
        "repo_full_name": "vercel/turborepo",
        "pr_number": 9271,
        "pr_file": "turborepo-tests/integration/tests/query/validation.t",
        "discussion_id": "1803647969",
        "commented_code": "@@ -0,0 +1,148 @@\n+Setup\n+  $ . ${TESTDIR}/../../../helpers/setup_integration_test.sh persistent_dependencies/10-too-many\n+\n+Validate that we get an error when we try to run multiple persistent tasks with concurrency 1\n+  $ ${TURBO} run build --concurrency=1\n+    x invalid task configuration\n+  \n+  Error:   x You have 2 persistent tasks but `turbo` is configured for concurrency of\n+    | 1. Set --concurrency to at least 3\n+  \n+  [1]\n+\n+However on query, we ignore this validation\n+  $ ${TURBO} query \"query { packages { items { tasks { items { fullName } } } } }\" | jq\n+   WARNING  query command is experimental and may change in the future\n+  {\n+    \"data\": {\n+      \"packages\": {\n+        \"items\": [\n+          {\n+            \"tasks\": {\n+              \"items\": []\n+            }\n+          },\n+          {\n+            \"tasks\": {\n+              \"items\": [\n+                {\n+                  \"fullName\": \"one#build\"\n+                }\n+              ]\n+            }\n+          },\n+          {\n+            \"tasks\": {\n+              \"items\": [\n+                {\n+                  \"fullName\": \"two#build\"\n+                }\n+              ]\n+            }\n+          }\n+        ]\n+      }\n+    }\n+  }\n+\n+Setup\n+  $ . ${TESTDIR}/../../../helpers/setup_integration_test.sh task_dependencies/invalid-dependency\n+  warning: re-init: ignored --initial-branch=main\n+\n+Validate that we get an error when trying to depend on a task that doesn't exist\n+  $ ${TURBO} run build2\n+    x Could not find \"app-a#custom\" in root turbo.json or \"custom\" in package\n+      ,-[turbo.json:27:1]\n+   27 |       \"dependsOn\": [\n+   28 |         \"app-a#custom\"\n+      :         ^^^^^^^^^^^^^^\n+   29 |       ]\n+      `----\n+  \n+  [1]\n+\n+However, we don't get an error when we query",
        "comment_created_at": "2024-10-16T19:07:19+00:00",
        "comment_author": "NicholasLYang",
        "comment_body": "I think it's necessary so people can use query to help refactor their repos into valid configurations for turbo. But yeah, we will have to watch out for panics. I have a larger plan to switch us to a compiler-y error model where we accumulate diagnostics and try to recover from errors as much as possible.",
        "pr_file_module": null
      }
    ]
  },
  {
    "discussion_id": "1965964253",
    "pr_number": 10023,
    "pr_file": "turborepo-tests/integration/tests/no-args.t",
    "created_at": "2025-02-21T18:07:23+00:00",
    "commented_code": "Override the filesystem cache directory\n         --concurrency <CONCURRENCY>\n             Limit the concurrency of task execution. Use 1 for serial (i.e. one-at-a-time) execution\n-        --continue\n-            Continue execution even if a task exits with an error or non-zero exit code. The default behavior is to bail\n+        --continue [<CONTINUE>]\n+            Specify which tasks should continue running when an error occurs. Use \"none\" to cancel all tasks. Use \"independent-tasks-only\" to continue running independent tasks and cancel dependent ones. Use \"all\" to continue running all tasks",
    "repo_full_name": "vercel/turborepo",
    "discussion_comments": [
      {
        "comment_id": "1965964253",
        "repo_full_name": "vercel/turborepo",
        "pr_number": 10023,
        "pr_file": "turborepo-tests/integration/tests/no-args.t",
        "discussion_id": "1965964253",
        "commented_code": "@@ -98,8 +98,8 @@ Make sure exit code is 2 when no args are passed\n             Override the filesystem cache directory\n         --concurrency <CONCURRENCY>\n             Limit the concurrency of task execution. Use 1 for serial (i.e. one-at-a-time) execution\n-        --continue\n-            Continue execution even if a task exits with an error or non-zero exit code. The default behavior is to bail\n+        --continue [<CONTINUE>]\n+            Specify which tasks should continue running when an error occurs. Use \"none\" to cancel all tasks. Use \"independent-tasks-only\" to continue running independent tasks and cancel dependent ones. Use \"all\" to continue running all tasks",
        "comment_created_at": "2025-02-21T18:07:23+00:00",
        "comment_author": "chris-olszewski",
        "comment_body": "Unsure of why the actual diff isn't showing on the [prysk diff output](https://github.com/vercel/turborepo/actions/runs/13460494959/job/37619607217#step:9:1126), but it's missing the possible values\r\n```suggestion\r\n            Specify which tasks should continue running when an error occurs. Use \"none\" to cancel all tasks. Use \"independent-tasks-only\" to continue running independent tasks and cancel dependent ones. Use \"all\" to continue running all tasks [default: none] [possible values: none, independent-tasks-only, all]\r\n```",
        "pr_file_module": null
      },
      {
        "comment_id": "1966052018",
        "repo_full_name": "vercel/turborepo",
        "pr_number": 10023,
        "pr_file": "turborepo-tests/integration/tests/no-args.t",
        "discussion_id": "1965964253",
        "commented_code": "@@ -98,8 +98,8 @@ Make sure exit code is 2 when no args are passed\n             Override the filesystem cache directory\n         --concurrency <CONCURRENCY>\n             Limit the concurrency of task execution. Use 1 for serial (i.e. one-at-a-time) execution\n-        --continue\n-            Continue execution even if a task exits with an error or non-zero exit code. The default behavior is to bail\n+        --continue [<CONTINUE>]\n+            Specify which tasks should continue running when an error occurs. Use \"none\" to cancel all tasks. Use \"independent-tasks-only\" to continue running independent tasks and cancel dependent ones. Use \"all\" to continue running all tasks",
        "comment_created_at": "2025-02-21T19:20:35+00:00",
        "comment_author": "jenseng",
        "comment_body": "fixed now... i ran into this issue a few times while iterating on the PR, my hunch is that prysk is treating `[...]` as a character class or something? \ud83e\udd14",
        "pr_file_module": null
      }
    ]
  }
]